"""Initial migration

Revision ID: 723870d04286
Revises: 
Create Date: 2024-06-02 13:51:42.454571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "723870d04286"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sports_id"), "sports", ["id"], unique=False)
    op.create_index(op.f("ix_sports_name"), "sports", ["name"], unique=False)
    op.create_index(op.f("ix_sports_slug"), "sports", ["slug"], unique=True)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("scheduled_start", sa.DateTime(), nullable=True),
        sa.Column("actual_start", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_name"), "events", ["name"], unique=False)
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)
    op.create_table(
        "selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_selections_id"), "selections", ["id"], unique=False)
    op.create_index(op.f("ix_selections_name"), "selections", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selections_name"), table_name="selections")
    op.drop_index(op.f("ix_selections_id"), table_name="selections")
    op.drop_table("selections")
    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_index(op.f("ix_events_name"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_sports_slug"), table_name="sports")
    op.drop_index(op.f("ix_sports_name"), table_name="sports")
    op.drop_index(op.f("ix_sports_id"), table_name="sports")
    op.drop_table("sports")
    # ### end Alembic commands ###
